### ISSUE TITLE
reference table generation issue

### ISSUE THREAD

**Issue by MoutonAlice** [diyabc/diyabcGUI#1]
Hello,
I am using the GUI interface for my DIYABC analyses. I have been runnning the program and some scenarios successfully the last few days but now I keep getting an error :

"something happened during the reftable generation:
Program of thread "6juillet reference table generation" exited (with return code 1) unsuccessfully. 
sOk[ipart]=18

I can't find any bug in the manual, I don't understand if this is a memory issue or what is wrong with the program.
I would highly appreciate any advices or suggestions,
Best regards
Alice

**Comment by fradav** [comment]
Hello, this is the repository for a brand new  interface for diyabc and is pretty much still work in progress. Please be patient while we are polishing and ironing some issues. In the meanwhile, please use the v2.1 if you need diyabc for your project now.

**Comment by MoutonAlice** [comment]
Many thanks! Good to know there will be a new interface soon. I am actually using the 2.1 but can't find any answer to my question. The bug report does not work and I can't seem to be able to contact the authors either. 
Thanks and good luck
Alice

**Comment by gdurif** [comment]
Hi, diyabc-2.1 is not maintained anymore. The upcoming new version will replace it (it should be available in a matter of days).
Best
