### ISSUE TITLE
Problem with the shiny app data validation prior to Simulate

### ISSUE THREAD

**Issue by jferrerobiol** [diyabc/diyabcGUI#107]
Hi gdurif,

Firstly, thank you for implementing RF DIYABC. I am on a mac and am therefore using the shiny app, and seem to have run into a bug.
I uploaded my SNP file and wrote a simple model. I validated all sections, which seemed to be fine. At the end when I validate, the message says, 'Project is ready for training set simulation'

However, when I run simulate, I get an error message saying ´Project is not ready. Check settings above´ I cannot however see any errors in the validation procedures.

To double-check this wasn't an issue with my SNP data file, I also uploaded the test SNP file, but I get the same error. The simulate section works fine if I upload the example data with its relevant metadata (header.txt etc). So this issue only seems to appear when starting a New Project

Thank you for your time

JFO

**Comment by jferrerobiol** [comment]
Just a small update. I cannot generate the project header.txt by doing ´Save Project´ or by looking in the R tmp directory (this for both the example SNP dataset and my own)

**Comment by jferrerobiol** [comment]
The same issue persisted when using the .bat app on a Windows machine. The version I have been using in both cases is v.1.1.0.

Thank you for your time and I apologise for the inconvenience!

**Comment by gdurif** [comment]
Hi, thanks for the feedback, no worries, I am the one to apologize for the trouble. I will look into it.

If there is no confidentiality issue, could you detail me the setup (historical scenario, priors, etc.) that you tried to use ?

Thanks in advance

**Comment by jferrerobiol** [comment]
Hi gdurif,

Thanks for your rapid answer. I tried different setups including the ones included in the indseq_SNP example and none has worked for me. I send you screenshots of one I am trying using 2 of the historical scenarios in the indseq_SNP example where you can see the error message I get:

<img width="1188" alt="Screenshot 2021-09-14 at 12 16 33" src="https://user-images.githubusercontent.com/30528650/133240440-79260786-93cc-4f69-9719-bfdee7a77068.png">
<img width="1176" alt="Screenshot 2021-09-14 at 12 16 50" src="https://user-images.githubusercontent.com/30528650/133240445-3c55ce07-b751-4c1d-bb9d-d88433715f7f.png">
<img width="1193" alt="Screenshot 2021-09-14 at 12 17 08" src="https://user-images.githubusercontent.com/30528650/133240450-24821617-4d5b-4482-870c-3ad3d865234d.png">
<img width="1172" alt="Screenshot 2021-09-14 at 12 17 24" src="https://user-images.githubusercontent.com/30528650/133240455-0279207e-aed4-49aa-9262-20424edaf0a4.png">
<img width="1158" alt="Screenshot 2021-09-14 at 12 17 45" src="https://user-images.githubusercontent.com/30528650/133240457-a4a49dc3-b26e-4a4d-b457-64a1d8c7a101.png">
<img width="1154" alt="Screenshot 2021-09-14 at 12 18 00" src="https://user-images.githubusercontent.com/30528650/133240460-69d3829b-3c6e-4b89-841f-14aea84e3d30.png">
<img width="1172" alt="Screenshot 2021-09-14 at 12 18 21" src="https://user-images.githubusercontent.com/30528650/133240462-e178131f-8b0b-4a6d-909e-898a399d6427.png">
<img width="1169" alt="Screenshot 2021-09-14 at 12 18 39" src="https://user-images.githubusercontent.com/30528650/133240463-d895777b-21bd-4f53-bdff-a36ac0a641bc.png">

Thank you very much for your help.

JFO

**Comment by aglorias** [comment]
Hello, I am having exactly the same issue. The data is validated and so are all other steps. I also get the "Project is ready for simulation" message, but then I try to click the "simulate" button and the orange message "Project is not read. "Check settings above" shows up.

Please let me know if you figure out how to make it run.
Thanks
Andrea

**Comment by Linkr1991** [comment]
Yes, same issue here! I am running it on windows 10, and tried both the shiny app and the .batt app. Ran into the same problem; it tells me that the project is ready for simulation, and then to check the settings above (all of which are validated). 
Please let me know if you figure out how to make it work!

**Comment by Linkr1991** [comment]
Other thing I noticed; when i save the project (without having been able to run the simulations) it only saves the .snp file is in the zip folder (similarly to jferrerobiol I think)

**Comment by kchapin1** [comment]
I'm also having this issue. Thanks for looking into it.

**Comment by jferrerobiol** [comment]
Hi @gdurif,
Any news on this issue? Do you think you will be able to solve the issue in the following days? Otherwise, is there a previous version that would not result in this issue that we could use in the meantime?
Thank you very much for your help and apologise for the inconvenience.
Really looking forward to using diyABC-RF!

**Comment by kchapin1** [comment]
Is this issue still being investigated? Just wanted to get a sense of a timeline - thanks.

**Comment by gdurif** [comment]
Hi @jferrerobiol @kchapin1 
Sorry for the late answer, I am a bit overwhelmed at work at the moment. I will look into it at the end of the week. In the mean time, you could try the previous release (but you may encounter some other issues that the current release was supposed to fix).
Best

**Comment by kchapin1** [comment]
Thanks for letting me know - excited to start using it.

**Comment by jferrerobiol** [comment]
Thank you very much @gdurif! FYI, using the previous version as you proposed is working well for me at the moment.

**Comment by gdurif** [comment]
Hi, I finally found the problem, new release build is now in progress, see issue #116 for a summary about this matter.

**Comment by gdurif** [comment]
The release is out: [v1.1.1-beta](https://github.com/diyabc/diyabcGUI/releases/tag/v1.1.1-beta)

**Comment by gdurif** [comment]
I am closing this issue. Do not hesitate to open a new one if you encounter any trouble.
