### ISSUE TITLE
Input containing only sequence.

### ISSUE THREAD

**Issue by dora-barle** [diyabc/diyabcGUI#110]
Hello,
I'm trying to run an input that only has sequence data and isn't accepting the input. I've tried with examples and the program works. Doesn't this version accept an input of sequences only?
Thank you so much!.

**Comment by dora-barle** [comment]
Hi Jaktykusuma!

Thank you for your answer. I've tried this in several ways, but it gives an error, and other times the matrix isn't read. Could you show me your matrix only with the sequences?

Cheers.

**Comment by gdurif** [comment]
Hi

@dora-barle Sorry for the late reply, I am buried in work at the moment. Which version of the software are you using ? We have a big problem with the latest release (that I downgraded to pre-release) at the moment. I will keep you updated when I have any news.

@jaktykusuma Thanks for the help

Best,

**Comment by dora-barle** [comment]
Hello
@gdurif 
No problem. Thank you for replying. I found out the error . Some of my sequences have "N". But there aren't many within each sequence, and not all sequences have them, but the program doesn't accept it. I kept "N" (I also tested with "-") because in the manual is writing that sequences may contain undetermined nucleotides, which will be denoted “N “ or “ - “. I did the test in several ways, and really if the sequence has a single "N" or "-", the program does not validate the data. The version is V.1.1.27 on Windows.

@jaktykusuma Thanks for the help

Best,

**Comment by gdurif** [comment]
@dora-barle Thanks for identifying the bug, I will check this (my memory tells me that I probably forgot to account for potential missing values in the code processing sequence data :disappointed: )

**Comment by dora-barle** [comment]
I thank you for building, maintaining, and updating the software. It has helped a lot. I'm happy to have contributed minimally to improve the program. =)
Best.

**Comment by gdurif** [comment]
Fixed in 4799fcd

Should be available in next release 1.1.1+ (currently in building)
