### ISSUE TITLE
Microsat mutation model

### ISSUE THREAD

**Issue by jaktykusuma** [diyabc/diyabcGUI#111]
Bonjour,

I'm using DIYABC RF GUI version to infer demographic history using microsatellite data. I tried to validate parameters on the mutation model, but after using default and modified numbers, both were unable to be validated. The consequences I wasn't able to continue simulating the data.

Please help, I really need to analyse my data.

Merci.

**Comment by gdurif** [comment]
Hi,
Sorry for my late reply. I am buried in work at the moment. We have a big problem with the latest release (that I downgraded to pre-release) at the moment. I will keep you updated when I have any news.
Best

**Comment by gdurif** [comment]
Hi, I finally found the problem, new release build is now in progress, see issue #116 for a summary about this matter.

**Comment by gdurif** [comment]
The release is out: [v1.1.1-beta](https://github.com/diyabc/diyabcGUI/releases/tag/v1.1.1-beta)

**Comment by gdurif** [comment]
Fixed by https://github.com/diyabc/diyabcGUI/commit/d41201218824319bab5939e78ac2ccdff6ae13d9
