### ISSUE TITLE
drawing of scenario 

### ISSUE THREAD

**Issue by pjeter77** [diyabc/diyabcGUI#145]
Hello,
I have three scenarios:

scenario 1

Ne1 Ne2 Ne3 Ne4 Ne5
0 sample 1
0 sample 2
0 sample 3
0 sample 4
0 sample 5
t3-db VarNe 1 N1
t3-db VarNe 2 N2
t3-db VarNe 3 N3
t3-db VarNe 4 N4
t3-db VarNe 5 N5
t3 merge 4 5
t3 merge 3 4
t3 merge 2 3
t3 merge 1 2
t3 VarNe 1 NA

scenario 2

Ne1 Ne2 Ne3 Ne4 Ne5
0 sample 1
0 sample 2
0 sample 3
0 sample 4
0 sample 5
t1-db VarNe 5 N5
t1 merge 4 5
t1 split 3 2 4 ra
t3-db varNe 4 N4
t3-db varNe 2 N2
t3 merge 1 4
t3 merge 1 2

scenario 3

Ne1 Ne2 Ne3 Ne4 Ne5
0 sample 1
0 sample 2
0 sample 3
0 sample 4
0 sample 5
t1-db VarNe 5 N5
t1 merge 4 5
t1 split 3 2 4 ra
t2-db varNe 4 N4
t2 merge 2 4
t3-db varNe 2 N2
t3 merge 1 2

When drawing in the old version DIYABC 2.1.0 the pictures are:
![oldversion](https://user-images.githubusercontent.com/82610850/208624264-9ba00869-f4a5-4650-be49-3b7032411398.png)

However, when using the new DIYABC-RF, then the pictures are:
![scenario1](https://user-images.githubusercontent.com/82610850/208624980-1bc9ea7a-0a17-4a87-8429-f6c5d0f4792a.png)
![scenario2](https://user-images.githubusercontent.com/82610850/208625000-3e537c58-dc69-4b84-989c-9296d945c98a.png)
![scenario3](https://user-images.githubusercontent.com/82610850/208625007-a73f623f-3f9f-49d5-be49-760e83398d7f.png)

The scenarios could be validated and the GUI does not call an error message and I can possibly run the simulations. Please, do you have any idea how to solve this problem?
Thank you!
Peter

**Comment by gdurif** [comment]
Hi,

Very sorry for the (very) late replies. The scenario drawing in the new DIYABC-RF still encounter some issues. However, it is "just aesthetics" and only concerns the drawing. It has no impact on the downstream analysis. You can run it.

Thanks for reporting this. We will try to fix it.

Best

**Comment by pjeter77** [comment]
Hi again, it stops when running training set simulations and the message "Issues with run, see log file" appears.
[Training_sim_Issues with run.log](https://github.com/diyabc/diyabcGUI/files/11311333/Training_sim_Issues.with.run.log)
