### ISSUE TITLE
Automatic download/update of diyabc/abcranger latest release

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabcGUI#16]
Write a script to automatically download latest release of `diyabc` and `abcranger`

**Comment by gdurif** [comment]
Two needs (but more or less same implementation):

- download latest release at package installation
- download latest release before standalone app build

**Comment by fradav** [comment]
Needs curl and jq.
Suppose you want the latest release of diyabc binary for windows
```sh
curl -s https://api.github.com/repos/diyabc/diyabc/releases | \
  jq -r '[[.[] |
    select(.draft != true) |
    select(.prerelease != true)][0] |
    .assets |
    .[] |
    select(.name | startswith("diyabc-windows")) |
    .browser_download_url][0]' | xargs curl -LO
```

**Comment by fradav** [comment]
If you want to do in R, the most obvious way is to get the https://api.github.com/repos/diyabc/diyabc/releases content in JSON and parse it for the binary link

**Comment by gdurif** [comment]
Done in `diyabcGUI` with `dl_latest_bin` and `dl_all_latest_bin` functions

Also check script `update_bin_release.R`
