### ISSUE TITLE
Errors encountered when install diyabc standalone on windows 

### ISSUE THREAD

**Issue by lusiran87** [diyabc/diyabcGUI#31]
Hi developers,
I tried to install diyabc standalone on Rstudio with R version 4.0.3 with "build_standalone.R" you provided in diyabcGUI-1.0.3.zip; However, the installation process failed with the following errror:

Finshed: Installing your Shiny package into electricShine framework
Error in system.file("extdata", "icon", package = my_package_name, lib.loc = library_path) : 
  'package' must be of length 1

but the package listed in the package catalogue, so I tried the code > diyabcGUI::diyabc(). GUI turned up but after I chose the data file, the GUI disppeared with the following error: 

Loading required package: shiny
Listening on http://127.0.0.1:3375
[1] "project directory: C:\\Users\\admin\\AppData\\Local\\Temp\\RtmpIfo76m\\diyabc56d876745c24"
Warning: Error in stri_c: can't find 'content'
 50: stri_c
  49: str_c
  47: check_mss_data_file
  46: check_data_file
  45: <observer>
   2: shiny::runApp
   1: diyabcGUI::diyabc

Could you help me figure out the problem?  I am planning to analyze my mss data with your work.

My system is Windows 10 X64 , RAM32GB, 6 cores.

Thank you very much in advance~

Siran

P.S. I also found DIYabc v2.1.0 and v2.0.4 can't run anymore.

**Comment by lusiran87** [comment]
I tried to install on another computer with Windows 10 X64 , RAM32GB, 16 cores. And encounter a new error:
Error in dl_latest_bin("diyabc") : Issue with download
PS: Warning message:
In dl_latest_bin("diyabc") :
  No binary file available for diyabc on windows. Contact DIYABC-RF support.

How to figure out this issue?

Siran

**Comment by gdurif** [comment]
Hi, the applicatiion is still under development, a few bug remain on master. A new pre-release will be available this week.

To use it (when it will be available), please follow the instructions in the corresponding section https://github.com/diyabc/diyabcGUI#installation in README file.

You will not need to use the script `build_standalone.R` which is only useful for us.
Best

**Comment by gdurif** [comment]
In addition, DIYABC v2 is not maintained anymore. DIYABC-RF will be its replacement.

**Comment by gdurif** [comment]
We have a new pre-release at https://github.com/diyabc/diyabcGUI/releases 

Please note that it is a pre-release. More will come in the next few weeks. Do not hesitate to install newer versions if available. If you encounter any bug, please fill an issue on github.

Best,
