### ISSUE TITLE
Bug in 2_historical_model_display.R?

### ISSUE THREAD

**Issue by lyl8086** [diyabc/diyabcGUI#33]
Hi,

Should '**rev_tree_d**' be '**rev_tree_df**' at line 260?

Yulong

**Comment by gdurif** [comment]
Thanks, fixed in 5a515da

**Comment by gdurif** [comment]
Out of curiosity, how did you end up finding this typo ? We are in the final development stage before official release and we are looking for alpha/beta testers.

**Comment by lyl8086** [comment]
Thanks for the fixing.
I was using the latest release from github, when I run scenario validation, the app exited with errors "no rev_tree_df". The console complained errors in function "tree_context", after doing some searches, I fould this typo.

**Comment by gdurif** [comment]
Ok great, it may remains a few bugs that we are currently fixing until the official release (that will happen in less than a month hopefully). Do not hesitate to report any other issue or suggestions while using it.
