### ISSUE TITLE
Graphical output generation v1.0.7

### ISSUE THREAD

**Issue by oscarhuanel** [diyabc/diyabcGUI#46]
Graphical output: modelchoice_out_graph_lda.png is not computed (section 7.3 of the user manual)

**Comment by gdurif** [comment]
Hi, sorry for the late response, I was away for the end of the year. This point is still a work in progress. modelchoice_out_graph_lda.png is not generated because of an issue in the underlying analysis tool, see #11. It should be fixed soon.

**Comment by oscarhuanel** [comment]
Hi, thanks for your answer. since approximately three days, I have not been able to run the simulations in DIYABC RF for Windows.

**Comment by gdurif** [comment]
Fixed in df4ec49
