### ISSUE TITLE
[RF][model choice] fix issue with oob error graph color when points overlap

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabcGUI#60]
![modelchoice_out_graph_error_versus_ntrees](https://user-images.githubusercontent.com/38720408/105687469-c54d2600-5ef8-11eb-8569-de59c5873fc9.png)

Colors seem to be different when too much points overlap.

**Comment by fradav** [comment]
replace or add with a smoothed curve ? Some people doesn't like smoothing...

**Comment by gdurif** [comment]
I'm going to reduce the alpha (increase the transparency) of the inner circles.

**Comment by fradav** [comment]
Is there already a function in ggplot2 to do that ? Because sorting the circles by overlapping precedence is non trivial

**Comment by gdurif** [comment]
i will use the same transparency on all points, if it is very high, the change of colors due to overlapping will be lower.

**Comment by gdurif** [comment]
Fixed in 10e8af1

Use alpha = 1 (no transparency) and reduce point size
