### ISSUE TITLE
[project setup][IndSeq SNP mode] Problem to upload and open IndSeq SNP data file

### ISSUE THREAD

**Issue by jorisbertrand** [diyabc/diyabcGUI#64]
Good morning, and congratulations for this promising update of diyabc.
I am experiencing some troubles while trying to upload an IndSeq SNP data file to the graphical user interface. 
In R, I get the following message in the consol: 

_Warning in parallel::mclapply(X[Split[[i]]], FUN, ..., mc.cores = as.integer(cl)) :
  all scheduled cores encountered errors in user code_
and then...
_[1] "Issue when checking IndSeq SNP data file content: arguments imply differing number of rows: 0, 1"
Warning: Error in split.default: first argument must be a vector
  52: split.default
  47: check_indseq_snp_data_file
  46: check_data_file
  45: <observer>
   2: shiny::runApp
   1: diyabc_

Do you think there is something wrong with the format of the file? For information, this file could be opened without problem in diyabc-2.1.0.
Thank you for your help!

**Comment by gdurif** [comment]
Hi, thanks for the report. We detected this issue yesterday evening and we are working on it.

**Comment by gdurif** [comment]
Fixed in 0a3a452

Will be included in the next release
