### ISSUE TITLE
Validate option in version 1.0.11

### ISSUE THREAD

**Issue by lukaszwalas** [diyabc/diyabcGUI#87]
Hello,

there is some problem with "Validate" option in version 1.0.11 - when I try to validate parameters for microsatellites data, the software does nothing and it's impossible to make further analyses.

In version 1.0.6, the same set of data works well and parameters are validated without any problem.

**Comment by gdurif** [comment]
Hi, thanks for the report, I will look into it and keep you updated.

**Comment by gdurif** [comment]
This is fixed in e5b6eb9. It will be available in the next release (>1.0.11), hopefully tomorrow.

**Comment by gdurif** [comment]
Fix available in release 1.0.11-beta2
